# Build Theme 
FROM composer AS php_builder 
WORKDIR /app/
COPY theme ./
RUN composer install && composer dump-autoload -o

## Build assets (JS, CSS)
FROM node:19 AS assets_builder
WORKDIR /app/
COPY theme ./
RUN npm i && npm run build

# Final Image 
FROM wordpress:fpm

#############
# APT TOOLS #
#############
RUN set -ex; \
    apt-get update && apt-get install -y sendmail libldap2-dev less; \ 
    apt-get purge -y --auto-remove; \
    rm -rf /var/lib/apt/lists/*

#######
# PHP #
#######

# Install PHP Extensions
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions; \
    install-php-extensions memcached ldap calendar gettext pdo_mysql sockets xsl

# Configure PHP Environment 
COPY ./conf/php/php.ini-production $PHP_INI_DIR/conf.d/custom.ini

###############
# OTHER TOOLS #
###############

# install wp-cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
RUN echo 'path: /var/www/html' > /wp-cli.yml

########
# MODS #
########

COPY conf/php/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf
# Give wp-cli write access
RUN chown www-data:www-data /var/www
USER www-data
COPY --from=assets_builder /app/assets/images /var/www/html/wp-content/themes/jjpro-portfolio/assets/images
COPY --from=assets_builder /app/build /var/www/html/wp-content/themes/jjpro-portfolio/build
COPY --from=php_builder /app/parts /var/www/html/wp-content/themes/jjpro-portfolio/parts
COPY --from=php_builder /app/patterns /var/www/html/wp-content/themes/jjpro-portfolio/patterns
COPY --from=php_builder /app/src /var/www/html/wp-content/themes/jjpro-portfolio/src
COPY --from=php_builder /app/templates /var/www/html/wp-content/themes/jjpro-portfolio/templates
COPY --from=php_builder /app/timber-views /var/www/html/wp-content/themes/jjpro-portfolio/timber-views
COPY --from=php_builder /app/vendor /var/www/html/wp-content/themes/jjpro-portfolio/vendor
COPY --from=php_builder /app/*.php /var/www/html/wp-content/themes/jjpro-portfolio/
COPY --from=php_builder /app/style.css /var/www/html/wp-content/themes/jjpro-portfolio/style.css
COPY --from=php_builder /app/theme.json /var/www/html/wp-content/themes/jjpro-portfolio/theme.json
COPY scripts/post-install.prod.sh /var/www/post-install.sh
SHELL ["/bin/bash"]
