# TODO after running: 
# 1. Complete initialization in browser
# 2. execute command to install Recommended plugins (Edit the file to your needs):
#     - `docker exec wordpress /var/www/post-install.dev.sh`

---
version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes: 
      - wordpress_data:/var/www/html
      - ./scripts/post-install.dev.sh:/var/www/post-install.dev.sh
      - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./theme:/var/www/html/wp-content/themes/jjpro-portfolio:ro
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=bn_wordpress
      - WORDPRESS_DB_PASSWORD=bn_wordpress
      - WORDPRESS_DB_NAME=bitnami_wordpress
      - WORDPRESS_DEBUG=true
      - |
        WORDPRESS_CONFIG_EXTRA=
        define( 'WP_DISABLE_FATAL_ERROR_HANDLER', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define('SMTP_HOST', 'mailhog');
        define('SMTP_PORT', 1025);
        define('SMTP_USER', 'from@test.com');
        define('SMTP_PASSWORD', 'test'); // This doesn't matter, mailhog won't check for authentication

  mariadb:
    image: bitnami/mariadb:10.6
    restart: unless-stopped
    environment:
      - MARIADB_PASSWORD=bn_wordpress
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_ROOT_PASSWORD=pass
    volumes:
      - db:/bitnami/mariadb

  mailhog:
    image: jcalonso/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # frontend

  nginx:
    image: nginx
    container_name: portfolio
    restart: unless-stopped
    ports: 
      - 8080:80
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - wordpress
  
volumes:
  db:
  wordpress_data:
