version: '3'

services:
  wordpress:
    image: jjpro/portfolio:bitnami
    container_name: portfolio # 8080
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - wordpress:/bitnami/wordpress
    networks: 
      - npm_br
      - default
    environment:
      ### Common
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - PHP_EXPOSE_PHP=no
      - PHP_MAX_EXECUTION_TIME=60 # 60s
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=50M
      
      ### Customize
      - WORDPRESS_BLOG_NAME=Blog
      - WORDPRESS_USERNAME=user
      - WORDPRESS_EMAIL=user@example.com
      - WORDPRESS_PASSWORD=bitnami

  mariadb:
    image: bitnami/mariadb:10.6
    restart: unless-stopped
    environment:
      - MARIADB_PASSWORD=bn_wordpress
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_ROOT_PASSWORD=G8W4A5%
    volumes:
      - db:/bitnami/mariadb
    networks: 
      - default

volumes:
  wordpress:
  db:

networks:
  npm_br: 
    external: true
  default: 
    internal: true