# TODO: 
# 1. expose port in `nginx` container, OR add `nginx` to network of another reverse proxy server (e.g. NPM)
# 2. Initial setup via the browser
# 3. execute command to install Recommended plugins (Edit the file to your needs):
#     - `docker exec wordpress /var/www/post-install.prod.sh`

---
version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
      - ./scripts/post-install.prod.sh:/var/www/post-install.prod.sh
      - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mariadb
    environment:
      ### Common
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

  mariadb:
    image: bitnami/mariadb:10.6
    container_name: wordpress-db
    restart: unless-stopped
    environment:
      - MARIADB_PASSWORD=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=wordpress
      - MARIADB_ROOT_PASSWORD=pass
    volumes:
      - db:/bitnami/mariadb

  nginx:
    image: nginx
    container_name: wordpress-nginx
    restart: unless-stopped
    # TODO Uncomment if you want to expose nginx directly, some folks, like me, would prefer attaching to NPM (Nginx Proxy Manager)'s network, and let NPM manage the proxy
    # ports: 
    #   - 8080:80
    volumes:
      - wordpress_data:/var/www/html
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db:
  wordpress_data: