name: Multi-Arch Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip image_build]') }}
    name: Build and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub Registry
        run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile
          tags: jjpro/portfolio-theme:latest

  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') }}
    name: Deploy new image on production server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Recreate container on production server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          command: cd /docker/docker-compose/portfolio && docker compose pull && docker compose up -d